ARG PROJECT_PATH=cpcx

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder
ARG PROJECT_PATH
WORKDIR /src
COPY . .
RUN dotnet publish ${PROJECT_PATH} -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app
COPY --from=builder /app .
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
EXPOSE 8080
ENTRYPOINT ["dotnet", "cpcx.dll"]
